### ISSUE TITLE
LambDynamicLights implementation doesn't seem to work

### ISSUE THREAD

**Issue by whatsaheart02** [tyrannus00/CleanF3#31] opened 2024-12-07 22:29 UTC
hi! i'm trying out clean f3 in a small 1.21.4 modpack and it seems that even with the option "hide lambdynamiclights' debug info" on, the supposed info still appears, is this a bug? thanks x)
![image](https://github.com/user-attachments/assets/db4b9b9b-07b4-42ee-be7e-66a3fa27de6c)
![image](https://github.com/user-attachments/assets/7c89eeef-c503-4c29-97c8-cf0963b807d8)

**Comment by LambdAurora** [comment] 2024-12-10 21:33
This is a duplicate of #30.

As I've warned the debug lines changed in LambDynamicLights' v4, which this mod's current code doesn't currently catch.

**Comment by tyrannus00** [comment] 2024-12-27 19:16
I have been very busy irl over the last few weeks, so I couldn't take care of this earlier. It will be fixed in the upcoming release soon!

**Closed by tyrannus00** 2024-12-27 19:16 UTC
